### ISSUE TITLE
Crashing if any attempt to parse Ars Technica feed, causing all later feeds to fail update as well.

### ISSUE THREAD

**Issue by bryanlyon** [m42e/ttrss_plugin-feediron#58]
The update daemon fails on any attempt to parse the ars technica feed
 
[08:49:24/6162] Base feed: http://feeds.arstechnica.com/arstechnica/index
[08:49:24/6162]  => 1970-01-01 00:00:00, 41 1
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to DOMXPath::query() must be an instance of DOMNode, boolean given in /usr/share/tt-rss/www/plugins/feediron/init.php:535
Stack trace:
#0 /usr/share/tt-rss/www/plugins/feediron/init.php(535): DOMXPath->query('//div[@class='c...', false)
#1 /usr/share/tt-rss/www/plugins/feediron/init.php(496): Feediron->cleanupNode(Object(DOMXPath), false, Array)
#2 /usr/share/tt-rss/www/plugins/feediron/init.php(389): Feediron->performXpath('<!DOCTYPE html>...', Array)
#3 /usr/share/tt-rss/www/plugins/feediron/init.php(174): Feediron->processArticle('<!DOCTYPE html>...', Array, 'http://arstechn...')
#4 /usr/share/tt-rss/www/plugins/feediron/init.php(81): Feediron->getNewContent('http://arstechn...', Array)
#5 /usr/share/tt-rss/www/include/rssfuncs.php(754): Feediron->hook_article_filter(Array)
#6 /usr/share/tt-rss/www/include/rssfuncs.php(201): update_rss_feed('41', true, false)
#7 /usr/share/tt-rss/www/update.php(160): update_daemon_common()
#8 {main}
  thrown in /usr/share/tt-rss/www/plugins/feediron/init.php on line 535

This is especially annoying because it affects all later feeds as well.

Running the latest version of feediron with the configuration as follows:

	"arstechnica.com": {
		"type": "xpath",
		"xpath": "div[contains(@class, 'article-content')]",
		"multipage": {
			"xpath": "nav[contains(@class, 'page-numbers')]\/span\/a[last()]",
			"append": true,
			"recursive": true
		},
			"cleanup": [
				"div[@class='corner-info']"
			],
			"force_charset": "utf-8"
		},

All other sites work if arstechnica is removed from the feediron config.

**Comment by irfus** [comment]
I'd been having the same issue. Fixed on my end by changing the configuration to, 

```
    "arstechnica.com": {
        "type": "xpath",
        "xpath": "div[contains(@class, 'article-content')]",
        "multipage": {
            "xpath": "nav[contains(@class, 'page-numbers')]/span/a[last()]",
            "append": true,
            "recursive": true
        },
```

**Comment by bryanlyon** [comment]
This problem has stopped happening to me.  But while it was occurring, it was happening no matter what the configuration was.  I believe it was crashing on something in the Ars Technica site itself.

**Comment by irfus** [comment]
It stopped happening on my end after I changed the configuration, and switched from mysql to pgsql for the backend. I guess maybe it was just some malformed feed items responsible, and the "fixes" working was a coincidence then. :-)

**Comment by irfus** [comment]
This started happening again. 
```
Uncaught TypeError: Argument 2 passed to DOMXPath::query() must be an instance of DOMNode or null, boolean given in /var/www/tt-rss/plugins/feediron/init.php:535 Stack trace: #0 /var/www/tt-rss/plugins/feediron/init.php(535): DOMXPath->query('//script', false) #1 /var/www/tt-rss/plugins/feediron/init.php(496): Feediron->cleanupNode(Object(DOMXPath), false, Array) #2 /var/www/tt-rss/plugins/feediron/init.php(389): Feediron->performXpath('0000A33E\r\n
```

Has to be a problem with the feed itself, but has anybody successfully debugged this?
